### ISSUE TITLE
Prodis : Site Web menus

### ISSUE THREAD

**Issue by sdfraus501** [d4e-digital-4-efficiency/prodis#1]
Bonjour Fares,

sur une page web comportant des menus nous constatons une bizarrerie de comportement. Jâi crée un ticket auprès du support Odoo qui n'a pas de solution.
A voir si tu as une idée pour résoudre ceci ?

Lorsque l'on clique sur un menu que l'on appelle par exemple "Entreprise" on accède à une page dédiée à l'entreprise avec du contenu.

Si l'on enrichit ce menu avec un sous menu par exemple "Blog", on ne peut plus accéder à la page entreprise dédiée. Cliquer sur le menu "père" ne devient plus possible.

Odoo me suggère de créer en plus du sous menu "Blog" le sous menu "Entreprise" mais cela créé une répétition.

Pour mieux te rendre compte voici  à quoi ca ressemble 👍 
![image](https://user-images.githubusercontent.com/75421531/107373492-e318ae80-6ae6-11eb-9df7-54ac80471ab5.png)

D'avance merci de ton aide,
Sacha.

**Comment by Fares-Hergli** [comment]
Salut Sacha,

J'ai trouvé une solution, mais j'ai voulu savoir si je dois faire mon commit sur le project "Prodis" d’après la tâche ou bien dans le projet "d4e-ch" d'après l'image.

Merci.

**Comment by sdfraus501** [comment]
Salut Farès,

 
Sur le projet « Prodis » stp.

 
Merci,

Sacha.

 
De : Fares-Hergli <notifications@github.com> 
Envoyé : jeudi, 11 février 2021 13:17
À : d4e-digital-4-efficiency/prodis <prodis@noreply.github.com>
Cc : Sacha (D4E) <sacha@digital4efficiency.ch>; Author <author@noreply.github.com>
Objet : Re: [d4e-digital-4-efficiency/prodis] Prodis : Site Web menus (#1)

 
Salut Sacha,

J'ai trouvé une solution, mais j'ai voulu savoir si je dois faire mon commit sur le project "Prodis" d’après la tâche ou bien dans le projet "d4e-ch" d'après l'image.

Merci.

**Comment by Fares-Hergli** [comment]
Salut Sacha,

J'ai créé un nouveau module "D4E Clickable Website Dropdown Menu"(D4E_clickable_website_dropdown_menu) qui rend tous les 'dropdown' du 'navbar' fonctionne avec 'hover' et le menu pére clickable .

Code source sur la branch "1_siteweb_menus" dans le commit "2fff109".
Merci.

**Comment by sdfraus501** [comment]
Salut Farès,

A passer en main + staging stp.

Merci,

Sacha.

**Comment by Fares-Hergli** [comment]
Salut,

C'est fait. Merci !

**Comment by sdfraus501** [comment]
Perfect merci !

Sacha.

**Comment by d4e-ch** [comment]
@sdfraus501 On passera tout en prod à la fin, n'est ce pas ? Si c'est le cas tu peux clore.
A+
